Fix using an invalid "wx" file mode in tools/dist/release.py.
I faced this issue when calling the `create_release_branch` command.

Apparently, open() requires exactly one of create/read/write/append modes.
While "wx" may have been accepted previously and worked in a non-standard
way, it now raises a ValueError [1, 2]:

  > python
  Python 3.10.12 (main, Nov  4 2025, 08:48:33) [GCC 11.4.0] on linux

  > python -c "open('/tmp/foo', 'wx')"
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ValueError: must have exactly one of create/read/write/append mode

* tools/dist/release.py
  (create_status_file_on_branch): Pass 'x' as file open mode instead of 'wx'.
   Using the exclusive create mode seems to imply write.

[1]: https://docs.python.org/3/library/functions.html#open
[2]: https://bugs.python.org/issue12760


git-svn-id: https://svn.apache.org/repos/asf/subversion/trunk@1930867 13f79535-47bb-0310-9956-ffa450edef68